### ISSUE TITLE
The Vault

### ISSUE THREAD

**Issue by arcanis** [JavidPack/WheresMyItems#1]
I like the idea of this mod, and I wanted to share possible improvements. If you don't want to implement them yourself (please don't take this wrong, I'm an small OSS developer myself so I know it's sometimes hard to find both time and motivation) I might be able to give it a try :)

So, the problem I see in your implementation is that despite being relatively roleplay, I don't think it solves the main issue of storage space, which is that it currently is awful to fetch items from chests. There's multiple reasons to that: you might have multiple chests that contain the same object but with different qualities, you might want a lot of different objects that are spread across multiple chests, etc. Your mod helps remembering, but it doesn't fix the core issue: the player will still need to move a lot a make a bunch of clicks for something that isn't objectively really fun. I would rather explore the world than my chests.

I've been toying with a new idea for a few days, and your mod provides me the opportunity to write it down. At its core, there's a new object type: the Vault. The Vault is very much like a chest - most notably, the Vault content is not shared across multiple Vault. However, the Vaults are different in that each Vault in the world can be searched from a single interface in order to access its content. There's three possible interfaces (obviously, only one of them should be implemented):

  - The first one would be to make the Vaults themselves contain the filter interface. When you open a Vault, there's a searchbar at the top of the Vault content window, and as you type an object name, the Vault content updates to only show the objects that match the name you've specified. Note that this new content window would **not** accept deposits: it would only support withdrawing objects (first because it will avoid requiring to find an empty Vault in which store the object, but also because it could be abused in order to never suffer ).

  - The second interface would be much similar, except that the interface described above would not be available by opening a Vault, but rather by using a shortcut. Since the Vaults don't spawn naturally in the world, we wouldn't have to add any kind of NPC check so that the player can't abuse the item.

  - The third interface is the most interesting one imo. The Vaults would be available from the very beginning of the game, for example sold by the Merchant for a small amount of money (1 gold?). The catch would be that the interface to search across the Vault network would only be made available by speaking to another new NPC, the Banker (who would obviously be [a goblin](http://harrypotter.wikia.com/wiki/Gringotts_Head_Goblin)). The banker would open the search window described in the previous interfaces, except that he would also take a small fee at each redrawal (50 silver?). I like this idea more than the others for two reasons:

    - It would allow to lock the search feature until later in the adventure while still allowing players to collect the Vault from the very beginning of the game. It's important, because otherwise by the time you unlock the Vault you will already have multiple chests, and moving your stuff from one to another would be pretty painful.

    - It acts as a small gold sink, and would require to be careful about it early in the adventure. Later on, players will be able to use it without worrying much because of the stack of gold they will have hoarded, but by then they will most probably have a lot of different objects and will desperately really need such a tool, so it's not an issue.

For now I haven't had time to look at how to implement this as a mod, but I think it could be interesting. Since you already have experience on the subject, do you think it could be done? I'm mainly concerned by the search bar, I don't know if it's possible to add UI elements like this.

**Comment by JavidPack** [comment]
Interesting ideas. Similar ideas have been floating around in the Terraria modding community for a while now, but it's hard to decide on the approach that is best. A lot of the ideas are based on Minecraft mods too.

I struggle with whether such a mod should be a tool available to all who install, or a gameplay element, limiting features until you progress far enough or craft/build enough components.

Having it be a gameplay feature would be neat, but some might just want to capabilities as a quality of life mod.

**Comment by Jofairden** [comment]
I see what jopo means regarding element availability. I don't know much, but I know blue is working on a mod that functions somewhat like this. I feel like it's best to wait right now and see what she comes up with, she already has everything planned out, sprites, and I think already begun programming it as well.

**Comment by arcanis** [comment]
I see - glad I mentioned this here before actually starting anything, then! :)

**Comment by JavidPack** [comment]
I feel that other mods, such as https://forums.terraria.org/index.php?threads/magic-storage.56294/ fill this need. I'll leave this mod as a simpler approach for those who still want to use chests.
